Various little docs fixups.

diff --git a/BitKeeper/triggers/post-commit b/BitKeeper/triggers/post-commit
--- a/BitKeeper/triggers/post-commit
+++ b/BitKeeper/triggers/post-commit
@@ -4,6 +4,7 @@
 TO=dev-public@mysql.com
 FROM=$USER@mysql.com
 INTERNALS=internals@lists.mysql.com
+DOCS=docs-commit@mysql.com
 LIMIT=10000
 
 if [ "$REAL_EMAIL" = "" ]
@@ -37,17 +38,39 @@ From: $FROM
 To: $INTERNALS
 Subject: bk commit into 3.23 tree
 
-Below is the list of changes that have just been commited into a local
-3.23. repository of $USER. When $USER does a push, they will be
-propogaged to the main repository and within 24 hours after the push into
-the public repository. For information on how to access
-the public repository see
-http://www.mysql.com/doc/I/n/Installing_source_tree.html
+Below is the list of changes that have just been committed into a local
+3.23 repository of $USER. When $USER does a push these changes will
+be propagated to the main repository and, within 24 hours after the
+push, to the public repository.
+For information on how to access the public repository
+see http://www.mysql.com/doc/I/n/Installing_source_tree.html
 
 EOF
   bk changes -v -r+
   bk cset -r+ -d
  ) | head -n $LIMIT | /usr/sbin/sendmail -t
+
+#++
+# docs-commit@ mail
+# Picks up anything under the Docs subdirectory (relevant for docs team).
+#--
+ bk changes -v -r+ | grep -q "  Docs/"
+ if [ $? -eq 0 ]
+ then
+  echo "Notifying docs list at $DOCS"
+  (
+    cat <<EOF
+List-ID: <bk.mysql-3.23>
+From: $FROM
+To: $DOCS
+Subject: bk commit - 3.23 tree (Manual)
+
+EOF
+  bk changes -v -r+
+  bk cset -r+ -d
+ ) | head -n $LIMIT | /usr/sbin/sendmail -t
+ fi
+
 else
- echo "commit failed because '$BK_STATUS', sorry life is hard..." 
+ echo "commit failed because '$BK_STATUS', you may need to re-clone..." 
 fi
