propagation to maria_repair_by_sort() and maria_repair_parallel() of bugfix made to maria_repair() yesterday. Fail "bk delta" (and thus "bk citool") if an added or modified line of a C/C++ file has white space at end of line
BitKeeper/triggers/pre-delta:
  detection gave false alarm on added newline
storage/maria/ma_check.c:
  propagation to maria_repair_by_sort() and maria_repair_parallel()
  of bugfix made to maria_repair() yesterday. No effect now as
  those two repair variants are never used with BLOCK_RECORD.

diff --git a/BitKeeper/triggers/pre-delta b/BitKeeper/triggers/pre-delta
--- a/BitKeeper/triggers/pre-delta
+++ b/BitKeeper/triggers/pre-delta
@@ -20,3 +20,18 @@ then
  exit 1
 fi
 
+# detect if C/C++ files have new trailing white space
+trailingblank=`echo $BK_FILE | egrep '\.(c|.h)'`
+if [ -n "$trailingblank" ]
+then
+    trailingblank=`bk diffs $BK_FILE | grep '^> .*[[:space:]]$'`
+    if [ -n "$trailingblank" ]
+        then
+        echo "bk diffs $BK_FILE | grep '^> .*[[:space:]]$'"
+        echo "reported white space at end of some added/modified lines"
+        echo ""
+        echo "Checkin FAILED!"
+        echo "Fix the problem and retry."
+        exit 1
+    fi
+fi
