Update to autoconf 2.52 Fix of InnoDB variables in SHOW VARIABLES Fix for ALTER TABLE and InnoDB

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -65,6 +65,12 @@ AC_DEFINE_UNQUOTED(SYSTEM_TYPE, "$SYSTEM_TYPE")
 AC_SUBST(MACHINE_TYPE)
 AC_DEFINE_UNQUOTED(MACHINE_TYPE, "$MACHINE_TYPE")
 
+# Detect intel x86 like processor
+BASE_MACHINE_TYPE=$MACHINE_TYPE
+case $MACHINE_TYPE in
+  i?86) BASE_MACHINE_TYPE=i386 ;;
+esac
+
 # Save some variables and the command line options for mysqlbug
 SAVE_CFLAGS="$CFLAGS"
 SAVE_CXXFLAGS="$CXXFLAGS"
@@ -81,7 +87,7 @@ AC_SUBST(CXXLDFLAGS)
 AC_PREREQ(2.12)dnl		Minimum Autoconf version required.
 
 AM_MAINTAINER_MODE
-AC_ARG_PROGRAM
+#AC_ARG_PROGRAM			# Automaticly invoked by AM_INIT_AUTOMAKE
 AM_SANITY_CHECK
 # This is needed is SUBDIRS is set
 AC_PROG_MAKE_SET
@@ -145,8 +151,10 @@ AM_PROG_LIBTOOL
 
 #AC_LIBTOOL_DLOPEN AC_LIBTOOL_WIN32_DLL AC_DISABLE_FAST_INSTALL AC_DISABLE_SHARED AC_DISABLE_STATIC
 
-# AC_PROG_INSTALL We should only need a AM_PROG_INSTALL
+# AC_PROG_INSTALL
 AC_PROG_INSTALL
+test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL_PROGRAM}'
+
 # Not critical since the generated file is distributed
 AC_PROG_YACC
 AC_CHECK_PROG(PDFMANUAL, pdftex, manual.pdf)
@@ -179,7 +187,8 @@ AC_DEFINE(SPRINTF_RETURNS_INT) AC_MSG_RESULT("int"),
  AC_DEFINE(SPRINTF_RETURNS_GARBAGE) AC_MSG_RESULT("garbage")))
    	
 
-# option, cache_name, variable
+# option, cache_name, variable,
+# code to execute if yes, code to exectute if fail
 AC_DEFUN(AC_SYS_COMPILER_FLAG,
 [
   AC_MSG_CHECKING($1)
@@ -188,7 +197,7 @@ AC_DEFUN(AC_SYS_COMPILER_FLAG,
   [
     CFLAGS="[$]OLD_CFLAGS $1"
     AC_TRY_RUN([int main(){exit(0);}],mysql_cv_option_$2=yes,mysql_cv_option_$2=no,mysql_cv_option_$2=no)
-  ])
+ ])
 
   CFLAGS="[$]OLD_CFLAGS"
   
@@ -288,6 +297,7 @@ AC_SUBST(CFLAGS)
 AC_SUBST(CXX)
 AC_SUBST(CXXFLAGS)
 AC_SUBST(LD)
+AC_SUBST(INSTALL_SCRIPT)
 
 export CC CFLAGS LD LDFLAGS
 
@@ -515,12 +525,22 @@ AC_ARG_ENABLE(assembler,
     [ ENABLE_ASSEMBLER=$enableval ],
     [ ENABLE_ASSEMBLER=no ]
     )
-# For now we only support assembler on i386 and sparc systems
-AM_CONDITIONAL(ASSEMBLER_x86, test "$ENABLE_ASSEMBLER" = "yes" -a "$MACHINE_TYPE" = "i386")
-AM_CONDITIONAL(ASSEMBLER_sparc, test "$ENABLE_ASSEMBLER" = "yes" -a "$MACHINE_TYPE" = "sparc")
-AM_CONDITIONAL(ASSEMBLER, test ASSEMBLER_x86 = "" -o ASSEMBLER_x86 = "")
 
-AC_MSG_CHECKING(whether to use RAID)
+AC_MSG_CHECKING(if we should use assembler functions)
+# For now we only support assembler on i386 and sparc systems
+AM_CONDITIONAL(ASSEMBLER_x86, test "$ENABLE_ASSEMBLER" = "yes" -a "$BASE_MACHINE_TYPE" = "i386")
+AM_CONDITIONAL(ASSEMBLER_sparc, test "$ENABLE_ASSEMBLER" = "yes" -a "$BASE_MACHINE_TYPE" = "sparc")
+AM_CONDITIONAL(ASSEMBLER, test "$ASSEMBLER_x86_TRUE" = "" -o "$ASSEMBLER_sparc_TRUE" = "")
+
+if test "$ASSEMBLER_TRUE" = ""
+then
+  AC_MSG_RESULT([yes])
+else
+  AC_MSG_RESULT([no])
+fi
+
+
+AC_MSG_CHECKING(if we should use RAID)
 AC_ARG_WITH(raid,
     [  --with-raid             Enable RAID Support],
     [   USE_RAID=$withval ],
@@ -563,9 +583,8 @@ AC_ARG_WITH(mysqld-user,
     )
 AC_SUBST(MYSQLD_USER)
 
-# Use Paul Eggerts macros from GNU tar to check for large file
-# support.
-AC_SYS_LARGEFILE
+# Use Paul Eggerts macros from GNU tar to check for large file support.
+MYSQL_SYS_LARGEFILE
 
 # Types that must be checked AFTER large file support is checked
 AC_TYPE_SIZE_T
@@ -764,8 +783,8 @@ case $SYSTEM_TYPE in
     ;;
   *hpux10.20*)
     echo "Enabling snprintf workaround for hpux 10.20"
-    CFLAGS="$CFLAGS -DHAVE_BROKEN_SNPRINTF -DSIGNALS_DONT_BREAK_READ"
-    CXXFLAGS="$CXXFLAGS -DHAVE_BROKEN_SNPRINTF -D_INCLUDE_LONGLONG -DSIGNALS_DONT_BREAK_READ"
+    CFLAGS="$CFLAGS -DHAVE_BROKEN_SNPRINTF -DSIGNALS_DONT_BREAK_READ -DDO_NOT_REMOVE_THREAD_WRAPPERS -DHPUX -DSIGNAL_WITH_VIO_CLOSE"
+    CXXFLAGS="$CXXFLAGS -DHAVE_BROKEN_SNPRINTF -D_INCLUDE_LONGLONG -DSIGNALS_DONT_BREAK_READ -DDO_NOT_REMOVE_THREAD_WRAPPERS -DHPUX -DSIGNAL_WITH_VIO_CLOSE"
     if test "$with_named_thread" = "no"
     then 
       echo "Using --with-named-thread=-lpthread"
@@ -774,8 +793,8 @@ case $SYSTEM_TYPE in
     ;;
   *hpux11.*)
     echo "Enabling pread/pwrite workaround for hpux 11"
-    CFLAGS="$CFLAGS -DHAVE_BROKEN_PREAD -DDONT_USE_FINITE -DHAVE_BROKEN_GETPASS -DNO_FCNTL_NONBLOCK"
-    CXXFLAGS="$CXXFLAGS -DHAVE_BROKEN_PREAD -DDONT_USE_FINITE -D_INCLUDE_LONGLONG -DNO_FCNTL_NONBLOCK"
+    CFLAGS="$CFLAGS -DHAVE_BROKEN_PREAD -DDONT_USE_FINITE -DHAVE_BROKEN_GETPASS -DNO_FCNTL_NONBLOCK -DDO_NOT_REMOVE_THREAD_WRAPPERS"
+    CXXFLAGS="$CXXFLAGS -DHAVE_BROKEN_PREAD -DDONT_USE_FINITE -D_INCLUDE_LONGLONG -DNO_FCNTL_NONBLOCK -DDO_NOT_REMOVE_THREAD_WRAPPERS"
     if test "$with_named_thread" = "no"
     then 
       echo "Using --with-named-thread=-lpthread"
@@ -1419,7 +1438,7 @@ MYSQL_TYPE_QSORT
 AC_FUNC_UTIME_NULL
 AC_FUNC_VPRINTF
 AC_CHECK_FUNCS(alarm bmove \
- chsize ftruncate rint finite fpsetmask fpresetsticky\
+ chsize ftruncate rint finite isnan fpsetmask fpresetsticky\
  cuserid fcntl fconvert poll \
  getrusage getpwuid getcwd getrlimit getwd index stpcpy locking longjmp \
  perror pread realpath readlink rename \
@@ -1728,7 +1747,7 @@ AC_ARG_WITH(readline,
 if test "$with_readline" = "yes"
 then
   readline_dir="readline"
-  readline_link="../readline/libreadline.a"
+  readline_link="\$(top_builddir)/readline/libreadline.a"
 else
   # This requires readline to be in a standard place. Mosty for linux
   # there readline may be a shared library.
@@ -1738,15 +1757,15 @@ fi
 AC_SUBST(readline_dir)
 AC_SUBST(readline_link)
 
-# Choose a character set
-dnl in order to add new charset, you must add charset name to
-dnl CHARSETS_AVAILABLE list and add the charset name to
-dnl sql/share/charsets/Index.  If the character set uses strcoll
-dnl or other special handling, you must also create
-dnl strings/ctype-$charset_name.c
+dnl In order to add new charset, you must add charset name to
+dnl this CHARSETS_AVAILABLE list and sql/share/charsets/Index.
+dnl If the character set uses strcoll or other special handling,
+dnl you must also create strings/ctype-$charset_name.c
 
+AC_DIVERT_PUSH(0)
 CHARSETS_AVAILABLE="big5 cp1251 cp1257 croat czech danish dec8 dos estonia euc_kr gb2312 gbk german1 greek hebrew hp8 hungarian koi8_ru koi8_ukr latin1 latin2 latin5 swe7 usa7 win1250 win1251 win1251ukr ujis sjis tis620"
 DEFAULT_CHARSET=latin1
+AC_DIVERT_POP
 
 dnl win1251 is deprecated - it's available, but not listed here in the help
 AC_ARG_WITH(charset,
@@ -2086,7 +2105,17 @@ EOF
   then
     sql_server_dirs="innobase $sql_server_dirs"
     echo "CONFIGURING FOR INNODB" 
-    (cd innobase && sh ./configure) \
+    if test ! -d "innobase"; then
+        # This should only happen when doing a VPATH build
+        echo "NOTICE: I have to make the Innobase directory: `pwd`/innobase"
+	mkdir "innobase" || exit 1
+    fi
+    rel_srcdir=
+    case "$srcdir" in
+	/* ) rel_srcdir="$srcdir" ;;
+	* )  rel_srcdir="../$srcdir" ;;
+    esac
+    (cd innobase && sh $rel_srcdir/innobase/configure) \
     || AC_MSG_ERROR([could not configure INNODB])
 
     echo "END OF INNODB CONFIGURATION"
@@ -2158,9 +2187,9 @@ AC_OUTPUT(Makefile extra/Makefile mysys/Makefile isam/Makefile \
  include/mysql_version.h
  , , [
   test -z "$CONFIG_HEADERS" || echo timestamp > stamp-h
-  rm -f $AVAILABLE_LANGUAGES_ERRORS_RULES
  ])
 
+rm -f $AVAILABLE_LANGUAGES_ERRORS_RULES
 echo
 echo "MySQL has a Web site at http://www.mysql.com/ which carries details on the"
 echo "latest release, upcoming features, and other information to make your"
@@ -2170,6 +2199,6 @@ echo
 echo "Remember to check the platform specific part in the reference manual for"
 echo "hints about installing on your platfrom. See the Docs directory."
 echo
-# This text is checked in ./Do-compile to se that the configure finished.
+# The following text is checked in ./Do-compile to se that the configure ends.
 echo "Thank you for choosing MySQL!"
 echo
