Update the SCO (now Caldera)/SysV tests.  This should allow OpenUnix8 to work automatically.  Thanks to Boyd Lynn Gerber for the patch.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -264,7 +264,16 @@ case "$target_os" in
        ;;
      esac
   ;;
-  sysv5uw7*) 
+  sysv5UnixWare*) 
+    if test "$GCC" != "yes"; then
+      # We are using built-in inline function
+      CFLAGS="$CFLAGS -Kalloca"
+      CXX="$CXX -DNO_CPLUSPLUS_ALLOCA"
+    else
+      CXX="$CXX -DNO_CPLUSPLUS_ALLOCA"
+    fi
+  ;;
+  sysv5OpenUNIX8*) 
     if test "$GCC" != "yes"; then
       # We are using built-in inline function
       CFLAGS="$CFLAGS -Kalloca"
@@ -274,7 +283,6 @@ case "$target_os" in
     fi
   ;;
 esac
-
 AC_SUBST(CC)
 AC_SUBST(CFLAGS)
 AC_SUBST(CXX)
@@ -990,7 +998,7 @@ fi
 if test "$with_named_thread" = "no"
 then
   AC_MSG_CHECKING("SCO UnixWare7 native threads")
-  if expr "$SYSTEM_TYPE" : ".*unixware7*" > /dev/null
+  if expr "$SYSTEM_TYPE" : ".*UnixWare*" > /dev/null
   then
     if test -f /usr/lib/libthread.so -o -f /usr/lib/libthreadT.so
     then
@@ -1014,6 +1022,45 @@ then
       AC_MSG_RESULT("yes")
     else
       { echo "configure: error: Can't find thread libs on SCO UnixWare7. See the Installation chapter in the Reference Manual." 1>&2; exit 1; };
+    fi
+  else
+    AC_MSG_RESULT("no")
+  fi
+fi
+
+# Hack for Caldera OpenUNIX8
+#
+if test "$with_named_thread" = "no"
+then
+  AC_MSG_CHECKING("OpenUNIX8 native threads")
+  if expr "$SYSTEM_TYPE" : ".*OpenUNIX*" > /dev/null
+  then
+    if test -f /usr/lib/libthread.so -o -f /usr/lib/libthreadT.so
+    then
+      MYSQL_REMOVE_SOCKET_FROM_LIBS_HACK
+      with_named_thread="-Kthread -lsocket -lnsl"
+      if expr "$SYSTEM_TYPE" : ".*unixware7.0.0" > /dev/null
+      then
+#        AC_DEFINE(HAVE_OpenUNIX8_THREADS)
+        AC_DEFINE(HAVE_UNIXWARE7_THREADS)
+      else
+#        AC_DEFINE(HAVE_OpenUNIX8_POSIX)
+        AC_DEFINE(HAVE_UNIXWARE7_POSIX)
+      fi
+      # We must have cc
+      AC_MSG_CHECKING("for gcc")
+      if expr "$CC" : ".*gcc.*"
+      then
+	{ echo "configure: error: On OpenUNIX8 and UnixWare7 MySQL must be compiled with cc. See the Installation chapter in the Reference Manual." 1>&2; exit 1; };
+      else
+#	CC="$CC -Kthread -DOpenUNIX8";
+#	CXX="$CXX -Kthread -DOpenUNIX8";
+	CC="$CC -Kthread -DUNIXWARE_7";
+	CXX="$CXX -Kthread -DUNIXWARE_7";
+      fi
+      AC_MSG_RESULT("yes")
+    else
+      { echo "configure: error: Can't find thread libs on Caldera OpenUNIX 8. See the Installation chapter in the Reference Manual." 1>&2; exit 1; };
     fi
   else
     AC_MSG_RESULT("no")
