test-make-manual	Cleaned up and added texi2dvi test.

diff --git a/Docs/Support/test-make-manual b/Docs/Support/test-make-manual
--- a/Docs/Support/test-make-manual
+++ b/Docs/Support/test-make-manual
@@ -2,30 +2,49 @@
 
 function die
 {
+  echo
   echo $1
   exit 1
 }
 
-echo
-echo "|---- Running makeinfo ----|"
+echo -n "Running makeinfo..."
 makeinfo --no-split -I . manual.texi
 
-[ $? != 0 ] && die "Manual has errors - fix before you commit"
+if [ $? != 0 ]; then
+    die "Manual has errors - fix before you commit"
+else
+    echo " Looks good."
+fi
 
-echo
-echo "|---- Running texi2html ----|"
+
+echo -n "Running texi2html..."
 /usr/bin/perl ./Support/texi2html -iso -number manual.texi
 
-[ $? != 0 ] && die "Manual has errors - fix before you commit"
+if [ $? != 0 ]; then
+    die "Manual has errors - fix before you commit"
+else
+    echo " Looks good."
+fi
+
+
+echo -n "Running texi2dvi..."
+texi2dvi --batch --quiet manual.texi
+
+if [ $? != 0 ]; then
+    die "Manual has errors - fix before you commit"
+else
+    echo " Looks good."
+fi
+
 
 [ -z $BROWSER ] && BROWSER=netscape 
 
 echo
+echo
 echo "Please examine your modifications in \`manual.html'."
-echo "For your convenience, I will show you the manual in $BROWSER"
-echo "If you would like to use a different browser, set BROWSER enviroment\
- variable" 
-echo "If this is a GUI browser, to get your shell prompt back, close the
- window"
+echo
+echo "If you would like to use a different browser, set the 'BROWSER' environment"
+echo "variable." 
+echo
 
-$BROWSER file://`pwd`/manual_toc.html
+$BROWSER file://`pwd`/manual_toc.html &
