Closes #270 Closes #271 Bugfixes in tokudb_load: Now supports -T (text) option along with other command line parameters Now supports -T option without newline at end of file (i.e. last data item ends with end of file)
git-svn-id: file:///svn/tokudb@1651 c7de825b-a66e-492c-adef-691d508d4ae1

diff --git a/utils/Makefile b/utils/Makefile
--- a/utils/Makefile
+++ b/utils/Makefile
@@ -70,7 +70,7 @@ TEST_GEN_HEX_FLAGS=-n $(TEST_GEN_HEX_NUMKEYS) -m $(TEST_GEN_HEX_LENGTHMIN) -M $(
 
 test_gen_hex:
 	#Generating $(TEST_GEN_HEX_NUMKEYS) keys.  [$(TEST_GEN_HEX_LENGTHMIN),$(TEST_GEN_HEX_LENGTHLIMIT)) bytes + identifier overhead
-	echo "Generating text input > db > text"
+	@echo "Generating text input > db > text"
 	rm -f $@.*.temp
 	./tokudb_gen $(TEST_GEN_HEX_FLAGS) > $@.gen.temp
 	$(UNSETTOKUENV) $(BDB_LOAD) $@.db.temp < $@.gen.temp
@@ -81,9 +81,12 @@ test_gen_hex:
 	if ! $(DIFF) -q $@.load_dump.temp $@.gen_sorted.temp; then echo "Test Failed!"; exit 1; fi
 	rm $@.*.temp
 
-test_load:
+test_load: test_load_hex test_load_text
+	
+
+test_load_hex:
 	#Generating $(TEST_GEN_HEX_NUMKEYS) keys.  [$(TEST_GEN_HEX_LENGTHMIN),$(TEST_GEN_HEX_LENGTHLIMIT)) bytes + identifier overhead
-	echo "Generating text input > db > text"
+	@echo "Generating text input > db > text"
 	rm -f $@.*.temp
 	./tokudb_gen $(TEST_GEN_HEX_FLAGS) > $@.gen.temp
 	$(UNSETTOKUENV) $(BDB_LOAD) $@.bdb.temp < $@.gen.temp
@@ -91,6 +94,26 @@ test_load:
 	$(UNSETTOKUENV) $(BDB_DUMP) $@.bdb.temp > $@.dump.bdb.temp
 	$(SETTOKUENV)   ./tokudb_dump $@.tokudb.temp > $@.dump.tokudb.temp
 	if ! $(DIFF) -q $@.dump.bdb.temp $@.dump.tokudb.temp; then echo "Test Failed!"; exit 1; fi
+
+TEST_GEN_TEXT_FLAGS=-n $(TEST_GEN_HEX_NUMKEYS) -m $(TEST_GEN_HEX_LENGTHMIN) -M $(TEST_GEN_HEX_LENGTHLIMIT) -r 5 -TP
+
+test_load_text: test_load_text_noendline
+	#Generating $(TEST_GEN_HEX_NUMKEYS) keys.  [$(TEST_GEN_HEX_LENGTHMIN),$(TEST_GEN_HEX_LENGTHLIMIT)) bytes + identifier overhead
+	@echo "Generating text input > db > text"
+	rm -f $@.*.temp
+	./tokudb_gen $(TEST_GEN_TEXT_FLAGS) > $@.gen.temp
+	$(UNSETTOKUENV) $(BDB_LOAD)   -T -t btree $@.bdb.temp < $@.gen.temp
+	$(SETTOKUENV)   ./tokudb_load -T -t btree $@.tokudb.temp < $@.gen.temp
+	$(UNSETTOKUENV) $(BDB_DUMP)   -p $@.bdb.temp > $@.dump.bdb.temp
+	$(SETTOKUENV)   ./tokudb_dump -p $@.tokudb.temp > $@.dump.tokudb.temp
+	if ! $(DIFF) -q $@.dump.bdb.temp $@.dump.tokudb.temp; then echo "Test Failed!"; exit 1; fi
+
+test_load_text_noendline:
+	@echo "Testing no end of line at end of file."
+	rm -f $@.*.temp
+	echo -en "key\nvalue" > $@.gen.temp
+	./tokudb_load -T -t btree $@.tokudb.temp < $@.gen.temp
+
 
 test_dump:
 	#Generating $(TEST_GEN_HEX_NUMKEYS) keys.  [$(TEST_GEN_HEX_LENGTHMIN),$(TEST_GEN_HEX_LENGTHLIMIT)) bytes + identifier overhead
