rlyon-5.0.0-alpha.patch

diff --git a/netware/BUILD/compile-netware-END b/netware/BUILD/compile-netware-END
--- a/netware/BUILD/compile-netware-END
+++ b/netware/BUILD/compile-netware-END
@@ -1,5 +1,11 @@
 #! /bin/sh                   
 
+# debug
+#set -x
+
+# stop on errors
+set -e
+
 path=`dirname $0`
 
 # clean
@@ -23,7 +29,7 @@ rm -rf Makefile.in.bk
 make clean bin-dist
 
 # mark the build
-for file in *.tar.gz
+for file in *.tar.gz *.zip
 do
 	if (expr "$file" : "mysql-[1-9].*" > /dev/null)
 	then
