make unit tests run only when java available

diff --git a/storage/ndb/ndbjtie/test/ndbjtie_unit_tests-t b/storage/ndb/ndbjtie/test/ndbjtie_unit_tests-t
--- a/storage/ndb/ndbjtie/test/ndbjtie_unit_tests-t
+++ b/storage/ndb/ndbjtie/test/ndbjtie_unit_tests-t
@@ -20,82 +20,41 @@ log="`pwd`/ndbjtie_unit_tests-t.log"
 rm -f "$log"
 touch "$log"
 
-# run test
-( cd .
-    echo "running test from directory:" >> "$log" 2>&1
-    echo "  `pwd`" >> "$log" 2>&1
-    if ! ./test_mutils_decimal.sh >> "$log" 2>&1; then
-	s="not "
-    fi
-    status="${s}ok 1 - test_mutils_decimal"
-    echo "$status" >> "$log" 2>&1
-    echo "" >> "$log" 2>&1
-    echo "$status"
-)
+test_counter=0
 
-# run test
-( cd .
-    echo "running test from directory:" >> "$log" 2>&1
-    echo "  `pwd`" >> "$log" 2>&1
-    if ! ./test_mutils_charsetmap.sh >> "$log" 2>&1; then
-	s="not "
-    fi
-    status="${s}ok 2 - test_mutils_charsetmap"
-    echo "$status" >> "$log" 2>&1
-    echo "" >> "$log" 2>&1
-    echo "$status"
-)
+#
+# Run a simpler shell script test, and report it as TAP
+#
+# Arguments:
+#   shell script hame
+#
+run_test()
+{
+    test_name=$1;
+    test_counter=$(expr $test_counter + 1)
+    script_name="$test_name.sh"
 
-# run test
-( cd .
-    echo "running test from directory:" >> "$log" 2>&1
-    echo "  `pwd`" >> "$log" 2>&1
-    if ! ./test_ndbjtie_library.sh >> "$log" 2>&1; then
-	s="not "
-    fi
-    status="${s}ok 3 - test_ndbjtie_library"
+    echo "running test '`pwd`/$script_name':" >> "$log" 2>&1
+    if [ ! -x "$script_name" ];
+    then
+        echo "File not executable or missing '`pwd`/$script_name':" >> "$log" 2>&1
+    else
+      ./$script_name >> "$log" 2>&1
+      if [ "$?" -ne "0" ]; then
+        s="not "
+      fi
+      status="${s}ok $test_counter - $test_name"
+    fi;
     echo "$status" >> "$log" 2>&1
     echo "" >> "$log" 2>&1
     echo "$status"
-)
+}
 
-# run test
-( cd .
-    echo "running test from directory:" >> "$log" 2>&1
-    echo "  `pwd`" >> "$log" 2>&1
-    if ! ./test_unload_mutils_decimal.sh >> "$log" 2>&1; then
-	s="not "
-    fi
-    status="${s}ok 4 - test_unload_mutils_decimal"
-    echo "$status" >> "$log" 2>&1
-    echo "" >> "$log" 2>&1
-    echo "$status"
-)
-
-# run test
-( cd .
-    echo "running test from directory:" >> "$log" 2>&1
-    echo "  `pwd`" >> "$log" 2>&1
-    if ! ./test_unload_mutils_charsetmap.sh >> "$log" 2>&1; then
-	s="not "
-    fi
-    status="${s}ok 5 - test_unload_mutils_charsetmap"
-    echo "$status" >> "$log" 2>&1
-    echo "" >> "$log" 2>&1
-    echo "$status"
-)
-
-# run test
-( cd .
-    echo "running test from directory:" >> "$log" 2>&1
-    echo "  `pwd`" >> "$log" 2>&1
-    if ! ./test_unload_ndbjtie_library.sh >> "$log" 2>&1; then
-	s="not "
-    fi
-    status="${s}ok 6 - test_unload_ndbjtie_library"
-    echo "$status" >> "$log" 2>&1
-    echo "" >> "$log" 2>&1
-    echo "$status"
-)
+run_test "test_mutils_decimal"
+run_test "test_mutils_charsetmap"
+run_test "test_ndbjtie_library"
+run_test "test_unload_mutils_decimal"
+run_test "test_unload_mutils_charsetmap"
+run_test "test_unload_ndbjtie_library"
 
 echo "done." >> "$log" 2>&1
